server:
  port: 8096
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.192.141
    username: leyou
    password: leyou
    virtual-host: /leyou
leyou:
  sms:
    accessKeyId: LTAI4Fv9RG4aSPajZ9AX7bcA # 你自己的accessKeyId
    accessKeySecret: lYIECKtsoU0YQXV5vWrfV6iIlTqyZA # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_183260447 # 模板名称
