server:
  port: 8096
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.192.141
    username: leyou
    password: leyou
    virtual-host: /leyou
leyou:
  sms:
    accessKeyId: LTAI4Fv9RG4aS # 你自己的accessKeyId
    accessKeySecret: lYIECKts # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_18 # 模板名称
